# -*- coding: utf-8 -*-
"""Kopia notatnika EKG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvQ65PqZ4lF8lmUBmtMk-mi8C-Ydnuu0

#ECG — Wykrywanie Chorób w Przestrzeni Częstotliwości

## Trzy klasy chorób:
| Klasa | Skrót | Opis |
|-------|-------|------|
| **Arytmia** | ARR | Nieregularny rytm serca |
| **Zastoinowa niewydołność serca** | CHF | Congestive Heart Failure |
| **Normalny rytm zatokowy** | NSR | Zdrowy sygnał referencyjny |

## Dataset: PhysioNet (MIT-BIH + BIDMC)
Dane pobierane automatycznie przez `wfdb` z PhysioNet.

## Modele:
- **Random Forest
- **SVM z RBF kernel
- **1D CNN na spektrum FFT

Instalacja bibliotek
"""

!pip install wfdb -q
!pip install scikit-learn matplotlib seaborn numpy scipy torch -q

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import wfdb
from scipy.signal import welch, butter, filtfilt
from scipy.fft import fft, fftfreq

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_curve, auc,
    accuracy_score, f1_score, precision_score, recall_score
)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

plt.rcParams.update({
    'figure.facecolor': '#0f0f1a', 'axes.facecolor': '#1a1a2e',
    'axes.edgecolor': '#444', 'text.color': 'white',
    'axes.labelcolor': 'white', 'xtick.color': 'white',
    'ytick.color': 'white', 'grid.color': '#333', 'figure.dpi': 100
})
COLORS = {'ARR': '#ff4d6d', 'CHF': '#4cc9f0', 'NSR': '#7bed9f'}
print('Biblioteki zaladowane!')
print(f'PyTorch: {torch.__version__} | GPU: {torch.cuda.is_available()}')

"""Pobieranie danych z PhysioNet

- **MIT-BIH Arrhythmia Database** → ARR
- **MIT-BIH Normal Sinus Rhythm Database** → NSR
- **BIDMC Congestive Heart Failure Database** → CHF

"""

# =========================
# GOOGLE DRIVE MOUNT
# =========================
from google.colab import drive
drive.mount('/content/drive')

# =========================
# SETUP
# =========================
import os
import wfdb
import numpy as np
from scipy.signal import welch, butter, filtfilt
from scipy.fft import fft

DATA_DIR = '/content/drive/MyDrive/ecg_data'
os.makedirs(DATA_DIR, exist_ok=True)

# =========================
# PARAMETRY
# =========================
FS = 360
SEGMENT_LEN = FS * 10
N_SEGMENTS_PER_RECORD = 20
MAX_RECORDS = 30

# =========================
# DATASETS (PhysioNet)
# =========================
ARR_DB = 'mitdb'
NSR_DB = 'nsrdb'

ARR_RECORDS = wfdb.get_record_list(ARR_DB)
NSR_RECORDS = wfdb.get_record_list(NSR_DB)

# =========================
# CACHE SYSTEM
# =========================
def record_paths(rec):
    return (
        os.path.join(DATA_DIR, rec + '.dat'),
        os.path.join(DATA_DIR, rec + '.hea')
    )

def is_downloaded(rec):
    dat, hea = record_paths(rec)
    return os.path.exists(dat) and os.path.exists(hea)

def download_record(rec, db):
    try:
        print(f'⬇️ Pobieranie: {rec}')
        wfdb.dl_database(db, DATA_DIR, records=[rec])

        if is_downloaded(rec):
            print(f'💾 Zapisano na Drive: {rec}')
        else:
            print(f'Nie zapisano poprawnie: {rec}')
    except Exception as e:
        print(f'Błąd: {rec} -> {str(e)[:50]}')

def load_record(rec, db):
    if not is_downloaded(rec):
        download_record(rec, db)
    else:
        print(f'Z Drive: {rec}')

    try:
        return wfdb.rdrecord(os.path.join(DATA_DIR, rec))
    except Exception as e:
        print(f'Load error: {rec}')
        return None

# =========================
# SIGNAL PROCESSING
# =========================
def bandpass_filter(data, lowcut=0.5, highcut=40.0, fs=FS, order=4):
    nyq = 0.5 * fs
    b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
    return filtfilt(b, a, data)

def extract_features(segment):
    freqs, psd = welch(segment, fs=FS, nperseg=512)

    total_power = np.trapz(psd, freqs) + 1e-10
    features = []

    for lo, hi in [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15)]:
        idx = (freqs >= lo) & (freqs <= hi)
        bp = np.trapz(psd[idx], freqs[idx]) if np.any(idx) else 0
        features.append(bp / total_power)

    features += [np.mean(psd), np.std(psd)]

    fft_vals = np.abs(fft(segment))[:30]
    fft_vals /= (np.max(fft_vals) + 1e-10)
    features.extend(fft_vals.tolist())

    return np.array(features, dtype=np.float32)

# =========================
# DATASETS (dodaj CHF)
# =========================
CHF_DB = 'chfdb'
CHF_RECORDS = wfdb.get_record_list(CHF_DB)

# =========================
# PROCESS (BEZ DATA LEAKAGE)
# =========================
def process_records_split(records, db, label, max_records):
    data = []

    for rec in records[:max_records]:
        record = load_record(rec, db)
        if record is None:
            continue

        sig = np.nan_to_num(record.p_signal[:,0])

        try:
            sig = bandpass_filter(sig)
        except:
            pass

        n_seg = min(N_SEGMENTS_PER_RECORD, len(sig)//SEGMENT_LEN)

        rec_features = []
        for i in range(n_seg):
            seg = sig[i*SEGMENT_LEN:(i+1)*SEGMENT_LEN]
            if len(seg) == SEGMENT_LEN:
                rec_features.append(extract_features(seg))

        if len(rec_features) > 0:
            data.append((np.array(rec_features), label))

        print(f'✔ {rec} -> {len(rec_features)} segmentów')

    return data

# =========================
# RUN
# =========================
print('--- START ---')

data_arr = process_records_split(ARR_RECORDS, ARR_DB, 'ARR', MAX_RECORDS)
data_nsr = process_records_split(NSR_RECORDS, NSR_DB, 'NSR', 15)
data_chf = process_records_split(CHF_RECORDS, CHF_DB, 'CHF', 15)

all_data = data_arr + data_nsr + data_chf

print('\n--- PODSUMOWANIE (rekordy) ---')
print(f'Liczba rekordów: {len(all_data)}')

# =========================
# SPLIT PO REKORDACH
# =========================
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(all_data, test_size=0.2, random_state=42)

# =========================
# ROZPAKOWANIE SEGMENTÓW
# =========================
def unpack(data):
    X, y = [], []
    for feats, label in data:
        for f in feats:
            X.append(f)
            y.append(label)
    return np.array(X), np.array(y)

X_train, y_train = unpack(train_data)
X_test, y_test = unpack(test_data)

print('\n--- PODSUMOWANIE (próbki) ---')
print('Train:', X_train.shape)
print('Test:', X_test.shape)

# =========================
# ENCODING + SCALING
# =========================
from sklearn.preprocessing import LabelEncoder, StandardScaler

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f'\nKlasy: {dict(zip(le.classes_, le.transform(le.classes_)))}')

"""Wizualizacja sygnałów i widm"""

from collections import defaultdict
sample_signals = {}
sample_map = [('ARR', ARR_RECORDS[0], 'mitdb'),
              ('NSR', NSR_RECORDS[0], 'nsrdb'),
              ('CHF', CHF_RECORDS[0], 'chfdb')]

for label, rec, db in sample_map:
    try:
        r = wfdb.rdrecord(rec, pn_dir=db)
        sig = r.p_signal[:SEGMENT_LEN, 0].astype(np.float64)
        sig = np.nan_to_num(sig)
        try: sig = bandpass_filter(sig)
        except: pass
        sample_signals[label] = sig
    except: pass

fig, axes = plt.subplots(3, 2, figsize=(18, 12))
fig.suptitle('EKG - analiza w dziedzinie czasu i czestotliwosci',
             fontsize=15, color='white', fontweight='bold')
titles = {'ARR': 'Arytmia (ARR)', 'NSR': 'Normalny rytm (NSR)',
          'CHF': 'Niewydolnosc serca (CHF)'}

for i, lbl in enumerate(['ARR', 'NSR', 'CHF']):
    if lbl not in sample_signals:
        continue
    sig = sample_signals[lbl]
    color = COLORS[lbl]
    t = np.arange(len(sig)) / FS
    ax_t = axes[i, 0]
    ax_t.plot(t[:FS*5], sig[:FS*5], color=color, linewidth=0.8)
    ax_t.set_title(f'{titles[lbl]} - sygnal (5s)', color='white')
    ax_t.set_xlabel('Czas [s]'); ax_t.set_ylabel('Amplituda [mV]')
    ax_t.grid(True, alpha=0.2)
    ax_f = axes[i, 1]
    fw, pw = welch(sig, fs=FS, nperseg=512)
    mask = fw <= 40
    ax_f.semilogy(fw[mask], pw[mask], color=color, linewidth=1.5)
    ax_f.fill_between(fw[mask], pw[mask], alpha=0.2, color=color)
    for lo, hi, nm, bc in [(0.04,0.15,'LF','#ff9f43'),(0.15,0.4,'HF','#54a0ff'),(5,15,'QRS','#5f27cd')]:
        ax_f.axvspan(lo, hi, alpha=0.12, color=bc, label=nm)
    ax_f.set_title(f'{lbl} - PSD (Welch)', color='white')
    ax_f.set_xlabel('Czestotliwosc [Hz]'); ax_f.set_ylabel('PSD [V2/Hz]')
    ax_f.set_xlim(0, 40); ax_f.grid(True, alpha=0.2)
    ax_f.legend(fontsize=8, facecolor='#1a1a2e', labelcolor='white')

plt.tight_layout()
plt.savefig('ecg_signals.png', dpi=120, bbox_inches='tight', facecolor='#0f0f1a')
plt.show()
print('Wykres zapisany: ecg_signals.png')

"""Podział danych train/test"""

def unpack(data):
    X, y = [], []
    for feats, label in data:
        for f in feats:
            X.append(f)
            y.append(label)
    return np.array(X), np.array(y)

X_all, y_all = unpack(all_data)

le = LabelEncoder()
y_enc = le.fit_transform(y_all)
classes = le.classes_
print(f'Klasy: {dict(zip(classes, le.transform(classes)))}')

X_train, X_test, y_train, y_test = train_test_split(
    X_all, y_enc, test_size=0.2, random_state=42, stratify=y_enc
)
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f'Trening: {X_train_sc.shape[0]} probek')
print(f'Test:    {X_test_sc.shape[0]} probek')
print(f'Cechy:   {X_train_sc.shape[1]}')

fig, ax = plt.subplots(figsize=(7, 4))
unique, counts = np.unique(y_all, return_counts=True)
bars = ax.bar(unique, counts, color=[COLORS[c] for c in unique],
              width=0.5, edgecolor='white', linewidth=0.5)
for bar, cnt in zip(bars, counts):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 1,
            str(cnt), ha='center', va='bottom', color='white', fontweight='bold')
ax.set_title('Rozklad klas w datasecie', color='white', fontsize=13)
ax.set_xlabel('Klasa'); ax.set_ylabel('Liczba probek')
ax.grid(True, axis='y', alpha=0.2)
plt.tight_layout(); plt.show()

"""Model 1 — Random Forest

> Dodaj cytat blokowy


"""

print('Trening Random Forest...')
rf = RandomForestClassifier(
    n_estimators=200, max_depth=20, min_samples_split=3,
    class_weight='balanced', random_state=42, n_jobs=-1
)
rf.fit(X_train_sc, y_train)
y_pred_rf = rf.predict(X_test_sc)
acc_rf = accuracy_score(y_test, y_pred_rf)
f1_rf  = f1_score(y_test, y_pred_rf, average='macro')
print(f'Accuracy: {acc_rf:.4f} ({acc_rf*100:.1f}%)')
print(f'F1-macro: {f1_rf:.4f}')
print(classification_report(y_test, y_pred_rf, target_names=classes))

"""Model 2 — SVM z jądrem RBF"""

print('Trening SVM (RBF)...')
svm = SVC(kernel='rbf', C=10.0, gamma='scale',
          class_weight='balanced', probability=True, random_state=42)
svm.fit(X_train_sc, y_train)
y_pred_svm = svm.predict(X_test_sc)
acc_svm = accuracy_score(y_test, y_pred_svm)
f1_svm  = f1_score(y_test, y_pred_svm, average='macro')
print(f'Accuracy: {acc_svm:.4f} ({acc_svm*100:.1f}%)')
print(f'F1-macro: {f1_svm:.4f}')
print(classification_report(y_test, y_pred_svm, target_names=classes))

"""Model 3 — 1D CNN na spektrum FFT (PyTorch)"""

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Uzywam: {DEVICE}')

class SpectralCNN(nn.Module):
    def __init__(self, input_dim, n_classes):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv1d(1, 32, kernel_size=5, padding=2),
            nn.BatchNorm1d(32), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(0.2),
            nn.Conv1d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(0.2),
            nn.Conv1d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128), nn.ReLU(), nn.AdaptiveAvgPool1d(8),
        )
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 8, 256), nn.ReLU(), nn.Dropout(0.4),
            nn.Linear(256, 64), nn.ReLU(),
            nn.Linear(64, n_classes)
        )
    def forward(self, x):
        return self.fc(self.conv(x.unsqueeze(1)))

X_tr_t = torch.tensor(X_train_sc, dtype=torch.float32)
y_tr_t = torch.tensor(y_train, dtype=torch.long)
X_te_t = torch.tensor(X_test_sc,  dtype=torch.float32)
y_te_t = torch.tensor(y_test,  dtype=torch.long)

train_dl = DataLoader(TensorDataset(X_tr_t, y_tr_t), batch_size=32, shuffle=True)
test_dl  = DataLoader(TensorDataset(X_te_t, y_te_t), batch_size=64, shuffle=False)

n_classes = len(classes)
cnn = SpectralCNN(X_train_sc.shape[1], n_classes).to(DEVICE)
print(f'Parametry CNN: {sum(p.numel() for p in cnn.parameters()):,}')

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50)
EPOCHS = 50
history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

print(f'Trening przez {EPOCHS} epok...')
for epoch in range(EPOCHS):
    cnn.train()
    tl, tc, tt = 0., 0, 0
    for xb, yb in train_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        logits = cnn(xb)
        loss = criterion(logits, yb)
        loss.backward(); optimizer.step()
        tl += loss.item() * len(xb)
        tc += (logits.argmax(1) == yb).sum().item(); tt += len(xb)
    scheduler.step()
    cnn.eval()
    vl, vc, vt = 0., 0, 0
    with torch.no_grad():
        for xb, yb in test_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            logits = cnn(xb)
            loss = criterion(logits, yb)
            vl += loss.item() * len(xb)
            vc += (logits.argmax(1) == yb).sum().item(); vt += len(xb)
    history['train_loss'].append(tl/tt); history['train_acc'].append(tc/tt)
    history['val_loss'].append(vl/vt);   history['val_acc'].append(vc/vt)
    if (epoch+1) % 10 == 0:
        print(f'Epoka {epoch+1:3d}/{EPOCHS} | '
              f'Loss {tl/tt:.4f}/{vl/vt:.4f} | '
              f'Acc {tc/tt*100:.1f}%/{vc/vt*100:.1f}%')

cnn.eval()
all_preds, all_probs = [], []
with torch.no_grad():
    for xb, _ in test_dl:
        logits = cnn(xb.to(DEVICE))
        probs = torch.softmax(logits, dim=1).cpu().numpy()
        all_probs.append(probs)
        all_preds.extend(logits.argmax(1).cpu().numpy())
y_pred_cnn = np.array(all_preds)
y_prob_cnn = np.vstack(all_probs)
acc_cnn = accuracy_score(y_test, y_pred_cnn)
f1_cnn  = f1_score(y_test, y_pred_cnn, average='macro')
print(f'CNN Accuracy: {acc_cnn:.4f} ({acc_cnn*100:.1f}%)')
print(f'CNN F1-macro: {f1_cnn:.4f}')

"""Macierze pomyłek"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Macierze Pomylek - Wszystkie Modele',
             fontsize=14, color='white', fontweight='bold')

model_preds = [
    ('Random Forest', y_pred_rf,  acc_rf,  'Blues'),
    ('SVM (RBF)',     y_pred_svm, acc_svm, 'Greens'),
    ('1D CNN (FFT)',  y_pred_cnn, acc_cnn, 'Purples'),
]

for ax, (name, y_pred, acc, cmap) in zip(axes, model_preds):
    cm = confusion_matrix(y_test, y_pred)
    cm_pct = cm.astype(float) / cm.sum(axis=1, keepdims=True) * 100
    sns.heatmap(cm_pct, annot=True, fmt='.1f', cmap=cmap,
                xticklabels=classes, yticklabels=classes, ax=ax,
                linewidths=0.5, linecolor='#333',
                annot_kws={'size': 13, 'weight': 'bold'})
    ax.set_title(f'{name}\nAccuracy: {acc*100:.1f}%', color='white', fontsize=11)
    ax.set_xlabel('Predykcja'); ax.set_ylabel('Rzeczywistosc')
    ax.tick_params(colors='white')

plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=120, bbox_inches='tight', facecolor='#0f0f1a')
plt.show()
print('Zapisano: confusion_matrices.png')

"""Krzywe ROC (wieloklasowe)"""

y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
y_prob_rf  = rf.predict_proba(X_test_sc)
y_prob_svm = svm.predict_proba(X_test_sc)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Krzywe ROC - One-vs-Rest (wieloklasowe)',
             fontsize=14, color='white', fontweight='bold')

model_probs = [
    ('Random Forest', y_prob_rf,  ['#ff6b9d','#f9ca24','#6c5ce7']),
    ('SVM (RBF)',     y_prob_svm, ['#fd79a8','#fdcb6e','#74b9ff']),
    ('1D CNN (FFT)',  y_prob_cnn, ['#ff4d6d','#ffd43b','#4cc9f0']),
]

for ax, (name, y_prob, cls_colors) in zip(axes, model_probs):
    ax.plot([0,1],[0,1], 'w--', alpha=0.4, linewidth=1)
    aucs = []
    for j, (cls_name, col) in enumerate(zip(classes, cls_colors)):
        fpr, tpr, _ = roc_curve(y_test_bin[:, j], y_prob[:, j])
        roc_auc = auc(fpr, tpr)
        aucs.append(roc_auc)
        ax.plot(fpr, tpr, color=col, linewidth=2.2,
                label=f'{cls_name} AUC={roc_auc:.3f}')
        ax.fill_between(fpr, tpr, alpha=0.08, color=col)
    ax.set_title(f'{name}\nMacro AUC: {np.mean(aucs):.3f}', color='white')
    ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate')
    ax.legend(fontsize=9, facecolor='#1a1a2e', labelcolor='white')
    ax.grid(True, alpha=0.2)

plt.tight_layout()
plt.savefig('roc_curves.png', dpi=120, bbox_inches='tight', facecolor='#0f0f1a')
plt.show()
print('Zapisano: roc_curves.png')

"""Historia treningu CNN"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
ep = range(1, EPOCHS+1)

ax1.plot(ep, history['train_loss'], '#ff4d6d', linewidth=2, label='Trening')
ax1.plot(ep, history['val_loss'],   '#4cc9f0', linewidth=2, label='Walidacja')
ax1.fill_between(ep, history['train_loss'], alpha=0.15, color='#ff4d6d')
ax1.fill_between(ep, history['val_loss'],   alpha=0.15, color='#4cc9f0')
ax1.set_title('CNN - Loss (Cross-Entropy)', color='white')
ax1.set_xlabel('Epoka'); ax1.set_ylabel('Loss')
ax1.legend(facecolor='#1a1a2e', labelcolor='white')
ax1.grid(True, alpha=0.2)

tr_acc = [x*100 for x in history['train_acc']]
va_acc = [x*100 for x in history['val_acc']]
ax2.plot(ep, tr_acc, '#7bed9f', linewidth=2, label='Trening')
ax2.plot(ep, va_acc, '#ffd43b', linewidth=2, label='Walidacja')
ax2.fill_between(ep, tr_acc, alpha=0.15, color='#7bed9f')
ax2.fill_between(ep, va_acc, alpha=0.15, color='#ffd43b')
ax2.axhline(max(va_acc), color='#ffd43b', linestyle=':',
            label=f'Max val: {max(va_acc):.1f}%')
ax2.set_title('CNN - Dokladnosc', color='white')
ax2.set_xlabel('Epoka'); ax2.set_ylabel('Accuracy [%]')
ax2.legend(facecolor='#1a1a2e', labelcolor='white')
ax2.grid(True, alpha=0.2)

plt.tight_layout()
plt.savefig('cnn_history.png', dpi=120, bbox_inches='tight', facecolor='#0f0f1a')
plt.show()

"""Ważność cech — Random Forest (Top 20)

Porównanie wszystkich modeli
"""

model_results = {
    'Random Forest': {'y_pred': y_pred_rf,  'color': '#ff6b9d', 'icon': 'RF'},
    'SVM (RBF)':     {'y_pred': y_pred_svm, 'color': '#74b9ff', 'icon': 'SVM'},
    '1D CNN (FFT)':  {'y_pred': y_pred_cnn, 'color': '#a29bfe', 'icon': 'CNN'},
}

metrics_vals = {}
print(f'{"Model":<20} {"Accuracy":>10} {"Precision":>10} {"Recall":>10} {"F1":>10}')
print('-' * 60)
for name, info in model_results.items():
    yp = info['y_pred']
    acc  = accuracy_score(y_test, yp)
    prec = precision_score(y_test, yp, average='macro', zero_division=0)
    rec  = recall_score(y_test, yp, average='macro', zero_division=0)
    f1   = f1_score(y_test, yp, average='macro', zero_division=0)
    metrics_vals[name] = [acc, prec, rec, f1]
    print(f'{name:<20} {acc:>10.3f} {prec:>10.3f} {rec:>10.3f} {f1:>10.3f}')

metric_labels = ['Accuracy', 'Precision\n(macro)', 'Recall\n(macro)', 'F1\n(macro)']
fig, ax = plt.subplots(figsize=(12, 6))
n_models = len(model_results)
bar_width = 0.22
x = np.arange(4)

for i, (name, info) in enumerate(model_results.items()):
    offset = (i - n_models/2 + 0.5) * bar_width
    vals = metrics_vals[name]
    bars = ax.bar(x + offset, vals, bar_width,
                  label=name, color=info['color'],
                  edgecolor='white', linewidth=0.5, alpha=0.9)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.005,
                f'{val:.3f}', ha='center', va='bottom',
                color='white', fontsize=8, fontweight='bold')

ax.set_title('Porownanie modeli - metryki klasyfikacji EKG',
             color='white', fontsize=13, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels(metric_labels, fontsize=10)
ax.set_ylabel('Wartosc metryki'); ax.set_ylim(0, 1.12)
ax.axhline(1.0, color='#555', linestyle='--', linewidth=0.8, alpha=0.5)
ax.legend(fontsize=10, facecolor='#1a1a2e', labelcolor='white')
ax.grid(True, axis='y', alpha=0.2)
plt.tight_layout()
plt.savefig('model_comparison.png', dpi=120, bbox_inches='tight', facecolor='#0f0f1a')
plt.show()

# =========================
# SLIDING WINDOW INFERENCE + WERYFIKACJA Z ADNOTACJAMI
# =========================

import wfdb
import numpy as np
import torch
from scipy.fft import fft
from scipy.signal import welch, butter, filtfilt
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# --- PARAMETRY ---
FS = 360
WINDOW_SEC = 10
WINDOW_LEN = FS * WINDOW_SEC
STEP_SEC = 5          # overlap 50% — okna co 5s
STEP_LEN = FS * STEP_SEC

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# =========================
# MAPOWANIE ANNOTACJI MIT-BIH → KLASY
# =========================
# Symbole annotacji wg standardu AAMI/MIT-BIH
ARR_BEATS = set(['V', 'F', 'f', 'A', 'a', 'J', 'S', 'E', 'j', 'n', 'e', 'Q'])
NSR_BEATS = set(['N', 'L', 'R', 'B', '/', 'p'])
# CHF — baza chfdb nie ma beat-level annotacji, weryfikujemy tylko ARR i NSR

def classify_annotation(ann_symbols):
    """
    Dla okna: jeśli > 10% uderzeń to annotacje arytmii → ARR, inaczej NSR.
    Zwraca etykietę lub None jeśli brak annotacji.
    """
    if len(ann_symbols) == 0:
        return None
    arr_count = sum(1 for s in ann_symbols if s in ARR_BEATS)
    ratio = arr_count / len(ann_symbols)
    return 'ARR' if ratio > 0.10 else 'NSR'


# =========================
# FEATURE EXTRACTION (identyczna jak przy treningu!)
# =========================
def bandpass_filter(data, lowcut=0.5, highcut=40.0, fs=FS, order=4):
    nyq = 0.5 * fs
    b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
    return filtfilt(b, a, data)

def extract_features(segment):
    freqs, psd = welch(segment, fs=FS, nperseg=512)
    total_power = np.trapz(psd, freqs) + 1e-10
    features = []
    for lo, hi in [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15)]:
        idx = (freqs >= lo) & (freqs <= hi)
        bp = np.trapz(psd[idx], freqs[idx]) if np.any(idx) else 0
        features.append(bp / total_power)
    features += [np.mean(psd), np.std(psd)]
    fft_vals = np.abs(fft(segment))[:30]
    fft_vals /= (np.max(fft_vals) + 1e-10)
    features.extend(fft_vals.tolist())
    return np.array(features, dtype=np.float32)


# =========================
# SLIDING WINDOW INFERENCE NA JEDNYM REKORDZIE
# =========================
def sliding_window_inference(record_path, model, scaler, le, db=None):
    """
    Wczytuje rekord, przepuszcza przez CNN okno po oknie.
    Zwraca:
        windows      — lista słowników {start_s, end_s, pred_label, pred_probs}
        ann_labels   — lista ground-truth etykiet per okno (lub None)
    """
    # Wczytaj sygnał
    try:
        rec = wfdb.rdrecord(record_path)
    except:
        rec = wfdb.rdrecord(record_path, pn_dir=db)

    sig = np.nan_to_num(rec.p_signal[:, 0])
    try:
        sig = bandpass_filter(sig)
    except:
        pass

    # Wczytaj annotacje jeśli istnieją
    ann = None
    try:
        ann = wfdb.rdann(record_path, 'atr')
    except:
        try:
            ann = wfdb.rdann(record_path, 'atr', pn_dir=db)
        except:
            pass  # baza CHF nie ma annotacji

    model.eval()
    windows = []
    ann_labels = []

    n_windows = (len(sig) - WINDOW_LEN) // STEP_LEN + 1

    for i in range(n_windows):
        start = i * STEP_LEN
        end   = start + WINDOW_LEN
        if end > len(sig):
            break

        segment = sig[start:end]

        # FFT feature extraction
        feat = extract_features(segment)
        feat_sc = scaler.transform(feat.reshape(1, -1))
        x = torch.tensor(feat_sc, dtype=torch.float32).to(DEVICE)

        with torch.no_grad():
            logits = model(x)
            probs  = torch.softmax(logits, dim=1).cpu().numpy()[0]
            pred_idx = logits.argmax(1).item()
            pred_label = le.inverse_transform([pred_idx])[0]

        windows.append({
            'start_s':    start / FS,
            'end_s':      end   / FS,
            'pred_label': pred_label,
            'pred_probs': dict(zip(le.classes_, probs.round(3))),
        })

        # Ground truth z annotacji
        if ann is not None:
            mask = (ann.sample >= start) & (ann.sample < end)
            syms = [ann.symbol[j] for j in range(len(ann.symbol)) if mask[j]]
            gt = classify_annotation(syms)
        else:
            gt = None
        ann_labels.append(gt)

    return windows, ann_labels


# =========================
# WERYFIKACJA NA WIELU REKORDACH
# =========================
def evaluate_on_records(record_list, db, model, scaler, le,
                         data_dir=DATA_DIR, max_records=10):
    """
    Pętla po rekordach → sliding window → zbieramy pred vs gt.
    Pomija okna bez annotacji (CHF lub brak pliku .atr).
    """
    all_preds = []
    all_gts   = []

    for rec_name in record_list[:max_records]:
        rec_path = os.path.join(data_dir, rec_name)
        print(f'Inference: {rec_name}')

        try:
            windows, ann_labels = sliding_window_inference(
                rec_path, model, scaler, le, db=db
            )
        except Exception as e:
            print(f'  Błąd: {e}')
            continue

        for win, gt in zip(windows, ann_labels):
            if gt is None:
                continue  # brak annotacji — pomijamy
            # filtrujemy tylko klasy które model zna
            if gt not in le.classes_:
                continue
            all_preds.append(win['pred_label'])
            all_gts.append(gt)

        matched = sum(p == g for p, g in zip(
            [w['pred_label'] for w in windows],
            ann_labels
        ) if g is not None)
        total = sum(1 for g in ann_labels if g is not None)
        if total:
            print(f'  Okna: {len(windows)} | Z annotacją: {total} | '
                  f'Poprawne: {matched} ({matched/total*100:.1f}%)')

    return np.array(all_preds), np.array(all_gts)


# =========================
# URUCHOMIENIE
# =========================
print('=== SLIDING WINDOW EVALUATION ===\n')

# ARR (mitdb — ma annotacje beat-level)
preds_arr, gts_arr = evaluate_on_records(
    ARR_RECORDS, ARR_DB, cnn, scaler, le, max_records=10
)

# NSR (nsrdb — ma annotacje)
preds_nsr, gts_nsr = evaluate_on_records(
    NSR_RECORDS, NSR_DB, cnn, scaler, le, max_records=8
)

# Połącz
all_preds_sw = np.concatenate([preds_arr, preds_nsr])
all_gts_sw   = np.concatenate([gts_arr,   gts_nsr])

print(f'\n=== WYNIKI SLIDING WINDOW (ARR + NSR) ===')
print(f'Łączna liczba okien z annotacją: {len(all_preds_sw)}')
print(f'Accuracy: {accuracy_score(all_gts_sw, all_preds_sw):.4f}')
print()
print(classification_report(all_gts_sw, all_preds_sw))

# Macierz konfuzji
labels_present = sorted(set(all_gts_sw) | set(all_preds_sw))
cm = confusion_matrix(all_gts_sw, all_preds_sw, labels=labels_present)
fig, ax = plt.subplots(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels_present, yticklabels=labels_present, ax=ax)
ax.set_xlabel('Predykcja'); ax.set_ylabel('Ground Truth (lekarz)')
ax.set_title('Sliding Window — CNN vs Annotacje MIT-BIH')
plt.tight_layout()
plt.savefig('sw_confusion_matrix.png', dpi=120, bbox_inches='tight')
plt.show()


# =========================
# PODGLĄD JEDNEGO REKORDU (okno po oknie)
# =========================
print('\n=== PRZYKŁAD: Rekord 100 (ARR) ===')
sample_rec = os.path.join(DATA_DIR, ARR_RECORDS[0])
windows, ann_labels = sliding_window_inference(
    sample_rec, cnn, scaler, le, db=ARR_DB
)

print(f'{"Start":>7} {"Koniec":>7} | {"Pred":>4} | {"GT":>4} | Prawdopodobieństwa')
print('-' * 65)
for win, gt in zip(windows[:20], ann_labels[:20]):
    match = '✔' if win['pred_label'] == gt else '✘'
    probs_str = ' | '.join(
        f"{k}:{v:.2f}" for k, v in sorted(win['pred_probs'].items())
    )
    print(f'{win["start_s"]:>6.1f}s {win["end_s"]:>6.1f}s | '
          f'{win["pred_label"]:>4} | {str(gt):>4} | {probs_str}  {match}')

# =========================
# NOWY PIPELINE — WINDOW-LEVEL LABELS
# =========================

import os, wfdb, numpy as np, torch, torch.nn as nn, torch.optim as optim
from scipy.signal import welch, butter, filtfilt
from scipy.fft import fft
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
import seaborn as sns

FS          = 360
WINDOW_SEC  = 10
WINDOW_LEN  = FS * WINDOW_SEC
STEP_SEC    = 5
STEP_LEN    = FS * STEP_SEC
DATA_DIR    = '/content/drive/MyDrive/ecg_data'
DEVICE      = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Symbole arytmiczne wg AAMI
ARR_SYMBOLS = set(['V','F','f','A','a','J','S','E','j','n','e','Q','!','+'])
NSR_SYMBOLS = set(['N','L','R','B','/','p'])

ARR_THRESHOLD = 0.05   # >5% arytmicznych uderzeń → okno = ARR


# =========================
# 1. FEATURE EXTRACTION
# =========================
def bandpass_filter(sig, lowcut=0.5, highcut=40.0, fs=FS, order=4):
    nyq = 0.5 * fs
    b, a = butter(order, [lowcut/nyq, highcut/nyq], btype='band')
    return filtfilt(b, a, sig)

def extract_features(segment, fs=FS):
    """
    Wektor cech łączący:
    - 4 pasma PSD (Welch) znormalizowane do total power
    - mean/std PSD
    - 60 współczynników FFT (amplituda + faza)
    - statystyki czasowe: mean, std, skewness, kurtosis, RMS, ZCR
    """
    from scipy.stats import skew, kurtosis as kurt

    # PSD bands
    freqs, psd = welch(segment, fs=fs, nperseg=512)
    total_power = np.trapz(psd, freqs) + 1e-10
    features = []
    for lo, hi in [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15),(15,40)]:
        idx = (freqs >= lo) & (freqs <= hi)
        bp  = np.trapz(psd[idx], freqs[idx]) if np.any(idx) else 0
        features.append(bp / total_power)
    features += [np.mean(psd), np.std(psd), np.max(psd),
                 freqs[np.argmax(psd)]]   # dominant frequency

    # FFT magnitude (pierwsze 60 binów) + faza
    fft_vals = fft(segment)
    mag  = np.abs(fft_vals)[:60]
    mag /= (np.max(mag) + 1e-10)
    phase = np.angle(fft_vals)[:60]
    features.extend(mag.tolist())
    features.extend(phase.tolist())

    # Time-domain
    features += [
        np.mean(segment),
        np.std(segment),
        float(skew(segment)),
        float(kurt(segment)),
        np.sqrt(np.mean(segment**2)),          # RMS
        np.sum(np.diff(np.sign(segment)) != 0) / WINDOW_LEN,  # ZCR
    ]

    return np.array(features, dtype=np.float32)


# =========================
# 2. BUDOWA DATASETU Z WINDOW-LEVEL LABELS
# =========================
def label_window_from_ann(ann_symbols):
    """Etykieta okna na podstawie uderzeń wewnątrz okna."""
    valid = [s for s in ann_symbols if s in ARR_SYMBOLS | NSR_SYMBOLS]
    if len(valid) == 0:
        return None
    arr_ratio = sum(1 for s in valid if s in ARR_SYMBOLS) / len(valid)
    return 'ARR' if arr_ratio > ARR_THRESHOLD else 'NSR'

def process_record_with_ann(rec_name, db, forced_label=None):
    """
    Wczytuje rekord + annotacje, dzieli na okna, etykietuje każde okno.
    forced_label: używane dla CHF (brak annotacji beat-level).
    Zwraca listę (features, label, rec_name).
    """
    rec_path = os.path.join(DATA_DIR, rec_name)

    try:
        rec = wfdb.rdrecord(rec_path)
    except:
        try:
            rec = wfdb.rdrecord(rec_name, pn_dir=db)
            # zapisz na Drive
            wfdb.dl_database(db, DATA_DIR, records=[rec_name])
            rec = wfdb.rdrecord(rec_path)
        except Exception as e:
            print(f'  ERR load {rec_name}: {e}')
            return []

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))
    try:
        sig = bandpass_filter(sig)
    except:
        pass

    # Annotacje
    ann = None
    if forced_label is None:
        try:
            ann = wfdb.rdann(rec_path, 'atr')
        except:
            try:
                ann = wfdb.rdann(rec_name, 'atr', pn_dir=db)
            except:
                pass

    samples = []
    n_windows = (len(sig) - WINDOW_LEN) // STEP_LEN + 1

    for i in range(n_windows):
        start = i * STEP_LEN
        end   = start + WINDOW_LEN
        if end > len(sig):
            break

        segment = sig[start:end]

        # Etykieta
        if forced_label is not None:
            label = forced_label
        elif ann is not None:
            mask  = (ann.sample >= start) & (ann.sample < end)
            syms  = [ann.symbol[j] for j in range(len(ann.sample)) if mask[j]]
            label = label_window_from_ann(syms)
            if label is None:
                continue   # okno bez czytelnych annotacji — pomiń
        else:
            continue

        feat = extract_features(segment)
        samples.append((feat, label, rec_name))

    return samples

# =========================
# 3. ZBIERANIE DANYCH
# =========================
print('Budowanie datasetu (window-level labels)...')

ARR_RECORDS = wfdb.get_record_list('mitdb')
NSR_RECORDS = wfdb.get_record_list('nsrdb')
CHF_RECORDS = wfdb.get_record_list('chfdb')

all_samples = []   # lista (feat, label, rec_name)

print('\n--- MIT-BIH ARR/NSR (annotacje beat-level) ---')
for rec in ARR_RECORDS[:30]:
    s = process_record_with_ann(rec, 'mitdb', forced_label=None)
    all_samples.extend(s)
    arr_c = sum(1 for _,l,_ in s if l=='ARR')
    nsr_c = sum(1 for _,l,_ in s if l=='NSR')
    print(f'  {rec}: {len(s)} okien | ARR={arr_c} NSR={nsr_c}')

print('\n--- NSR DB ---')
for rec in NSR_RECORDS[:15]:
    s = process_record_with_ann(rec, 'nsrdb', forced_label=None)
    all_samples.extend(s)
    print(f'  {rec}: {len(s)} okien')

print('\n--- CHF DB (forced label=CHF) ---')
for rec in CHF_RECORDS[:15]:
    s = process_record_with_ann(rec, 'chfdb', forced_label='CHF')
    all_samples.extend(s)
    print(f'  {rec}: {len(s)} okien')

# Statystyki
from collections import Counter
label_counts = Counter(l for _,l,_ in all_samples)
print(f'\nŁącznie okien: {len(all_samples)}')
print(f'Rozkład: {dict(label_counts)}')


# =========================
# 4. SPLIT — PO REKORDACH (bez data leakage)
# =========================
X_raw    = np.array([s[0] for s in all_samples])
y_raw    = np.array([s[1] for s in all_samples])
groups   = np.array([s[2] for s in all_samples])

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X_raw, y_raw, groups))

X_train, X_test = X_raw[train_idx], X_raw[test_idx]
y_train, y_test = y_raw[train_idx], y_raw[test_idx]

print(f'\nTrain: {len(X_train)} okien | Test: {len(X_test)} okien')
print(f'Train rekordy: {len(set(groups[train_idx]))} | '
      f'Test rekordy: {len(set(groups[test_idx]))}')
print(f'Train rozkład: {dict(Counter(y_train))}')
print(f'Test rozkład:  {dict(Counter(y_test))}')

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)
print(f'Klasy: {list(le.classes_)}')

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)


# =========================
# 5. CLASS WEIGHTS (nierównomierny rozkład)
# =========================
from sklearn.utils.class_weight import compute_class_weight
cw = compute_class_weight('balanced', classes=np.unique(y_train_enc), y=y_train_enc)
class_weights = torch.tensor(cw, dtype=torch.float32).to(DEVICE)
print(f'Class weights: {dict(zip(le.classes_, cw.round(3)))}')


# =========================
# 6. CNN — PRZEPROJEKTOWANA
# =========================
class WindowCNN(nn.Module):
    """
    1D CNN na wektorze cech FFT+PSD+time-domain.
    Residual connections stabilizują trening na krótkich wektorach.
    """
    def __init__(self, input_dim, n_classes):
        super().__init__()
        self.input_bn = nn.BatchNorm1d(1)

        self.block1 = nn.Sequential(
            nn.Conv1d(1, 64, kernel_size=7, padding=3),
            nn.BatchNorm1d(64), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(64, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64), nn.GELU(),
        )
        self.pool1 = nn.MaxPool1d(2)

        self.block2 = nn.Sequential(
            nn.Conv1d(64, 128, kernel_size=5, padding=2),
            nn.BatchNorm1d(128), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128), nn.GELU(),
        )
        self.pool2 = nn.MaxPool1d(2)

        self.block3 = nn.Sequential(
            nn.Conv1d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm1d(256), nn.GELU(), nn.Dropout(0.3),
        )
        self.gap = nn.AdaptiveAvgPool1d(1)

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.4),
            nn.Linear(128, 64),  nn.GELU(),
            nn.Linear(64, n_classes),
        )

    def forward(self, x):
        x = x.unsqueeze(1)           # (B, 1, input_dim)
        x = self.input_bn(x)
        x = self.pool1(self.block1(x))
        x = self.pool2(self.block2(x))
        x = self.gap(self.block3(x))
        return self.fc(x)


# =========================
# 7. TRENING Z EARLY STOPPING
# =========================
X_tr_t = torch.tensor(X_train_sc, dtype=torch.float32)
y_tr_t = torch.tensor(y_train_enc, dtype=torch.long)
X_te_t = torch.tensor(X_test_sc,  dtype=torch.float32)
y_te_t = torch.tensor(y_test_enc,  dtype=torch.long)

train_dl = DataLoader(TensorDataset(X_tr_t, y_tr_t),
                      batch_size=64, shuffle=True,  drop_last=True)
test_dl  = DataLoader(TensorDataset(X_te_t, y_te_t),
                      batch_size=128, shuffle=False)

n_classes = len(le.classes_)
model = WindowCNN(X_train_sc.shape[1], n_classes).to(DEVICE)
print(f'\nParametry CNN: {sum(p.numel() for p in model.parameters()):,}')
print(f'Input dim: {X_train_sc.shape[1]}')

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-3)
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=1e-3, epochs=80,
    steps_per_epoch=len(train_dl), pct_start=0.2
)

EPOCHS       = 80
PATIENCE     = 12
best_f1      = 0.0
patience_cnt = 0
best_state   = None
history      = {'train_loss':[],'train_acc':[],'val_loss':[],'val_acc':[],'val_f1':[]}

print(f'\nTrening przez max {EPOCHS} epok (early stopping patience={PATIENCE})...\n')

for epoch in range(EPOCHS):
    model.train()
    tl, tc, tt = 0., 0, 0
    for xb, yb in train_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        tl += loss.item()*len(xb)
        tc += (model(xb).argmax(1)==yb).sum().item()
        tt += len(xb)

    model.eval()
    vl, vc, vt, vp, vg = 0., 0, 0, [], []
    with torch.no_grad():
        for xb, yb in test_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            logits = model(xb)
            vl += criterion(logits, yb).item()*len(xb)
            preds = logits.argmax(1)
            vc += (preds==yb).sum().item()
            vt += len(xb)
            vp.extend(preds.cpu().numpy())
            vg.extend(yb.cpu().numpy())

    val_f1 = f1_score(vg, vp, average='macro')
    history['train_loss'].append(tl/tt)
    history['train_acc'].append(tc/tt)
    history['val_loss'].append(vl/vt)
    history['val_acc'].append(vc/vt)
    history['val_f1'].append(val_f1)

    if (epoch+1) % 5 == 0:
        print(f'Epoka {epoch+1:3d} | '
              f'Loss {tl/tt:.4f}/{vl/vt:.4f} | '
              f'Acc {tc/tt*100:.1f}%/{vc/vt*100:.1f}% | '
              f'F1 {val_f1:.4f}')

    if val_f1 > best_f1:
        best_f1   = val_f1
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_cnt = 0
    else:
        patience_cnt += 1
        if patience_cnt >= PATIENCE:
            print(f'\nEarly stopping @ epoka {epoch+1} | Best F1={best_f1:.4f}')
            break

model.load_state_dict(best_state)
print(f'\nZaładowano best model (F1={best_f1:.4f})')


# =========================
# 8. EWALUACJA KOŃCOWA
# =========================
model.eval()
all_preds, all_probs = [], []
with torch.no_grad():
    for xb, _ in test_dl:
        logits = model(xb.to(DEVICE))
        all_probs.extend(torch.softmax(logits,1).cpu().numpy())
        all_preds.extend(logits.argmax(1).cpu().numpy())

y_pred_final = np.array(all_preds)
print('\n=== RAPORT KOŃCOWY ===')
print(f'Accuracy: {accuracy_score(y_test_enc, y_pred_final):.4f}')
print(f'F1-macro: {f1_score(y_test_enc, y_pred_final, average="macro"):.4f}')
print()
print(classification_report(y_test_enc, y_pred_final, target_names=le.classes_))

cm = confusion_matrix(y_test_enc, y_pred_final)
fig, ax = plt.subplots(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_, ax=ax)
ax.set_xlabel('Predykcja'); ax.set_ylabel('Ground Truth (lekarz)')
ax.set_title('Window-level CNN vs Annotacje')
plt.tight_layout()
plt.savefig('window_cm.png', dpi=120, bbox_inches='tight')
plt.show()

# Zapisz model
torch.save({
    'model_state': model.state_dict(),
    'scaler':      scaler,
    'le':          le,
    'input_dim':   X_train_sc.shape[1],
    'n_classes':   n_classes,
}, os.path.join(DATA_DIR, 'window_cnn.pt'))
print('Model zapisany: window_cnn.pt')

# =========================
# SZYBKI PIPELINE — PARALLEL + VECTORIZED
# =========================
import os, wfdb, numpy as np, torch
from scipy.signal import welch, butter, filtfilt
from scipy.fft import fft
from scipy.stats import skew, kurtosis as kurt
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
import random, warnings
warnings.filterwarnings('ignore')

FS         = 360
WINDOW_LEN = FS * 10
STEP_LEN   = FS * 5
DATA_DIR   = '/content/drive/MyDrive/ecg_data'
N_WORKERS  = 8   # wątki I/O — zwiększ do 16 jeśli Colab Pro

ARR_SYMBOLS = frozenset(['V','F','f','A','a','J','S','E','j','n','e','Q','!'])
NSR_SYMBOLS = frozenset(['N','L','R','B','/'])

MITDB_ARR_RECORDS = [
    '200','201','202','203','205','207','208','209','210',
    '212','213','214','215','217','219','220','221','222',
    '223','228','230','231','232','233','234'
]
MITDB_NSR_RECORDS = [
    '100','101','103','105','106','108','112','113',
    '114','115','116','117','118','119'
]

# =========================
# 1. BATCH DOWNLOAD — najpierw wszystko ściągnij
# =========================
def download_if_missing(rec_name, db):
    dat = os.path.join(DATA_DIR, rec_name + '.dat')
    hea = os.path.join(DATA_DIR, rec_name + '.hea')
    if os.path.exists(dat) and os.path.exists(hea):
        return True
    try:
        wfdb.dl_database(db, DATA_DIR, records=[rec_name])
        return True
    except:
        return False

def batch_download(records, db):
    print(f'  Pobieranie {len(records)} rekordów ({db})...')
    with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:
        futures = {ex.submit(download_if_missing, r, db): r for r in records}
        ok = sum(1 for f in as_completed(futures) if f.result())
    print(f'  OK: {ok}/{len(records)}')

print('=== BATCH DOWNLOAD ===')
batch_download(MITDB_ARR_RECORDS, 'mitdb')
batch_download(MITDB_NSR_RECORDS, 'mitdb')
batch_download(wfdb.get_record_list('nsrdb')[:15], 'nsrdb')
batch_download(wfdb.get_record_list('chfdb')[:15], 'chfdb')


# =========================
# 2. VECTORIZED FEATURE EXTRACTION
#    Wszystkie okna jednego rekordu naraz — bez pętli Python
# =========================
_BP_BANDS = [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15),(15,40)]

def extract_features_batch(windows_2d, fs=FS):
    """
    windows_2d: (N, WINDOW_LEN) float32
    Zwraca:    (N, n_features) float32
    Wszystkie operacje zwektoryzowane po osi 0.
    """
    N = len(windows_2d)

    # --- FFT (wszystkie okna naraz) ---
    fft_vals  = np.fft.rfft(windows_2d, axis=1)          # (N, WINDOW_LEN//2+1)
    mag_full  = np.abs(fft_vals)                          # (N, WINDOW_LEN//2+1)
    mag60     = mag_full[:, :60]
    mag60    /= (mag60.max(axis=1, keepdims=True) + 1e-10)
    phase60   = np.angle(fft_vals[:, :60])

    # --- Welch PSD (batch przez pętlę — welch nie jest wektorowy, ale liczymy raz) ---
    freqs, _ = welch(windows_2d[0], fs=fs, nperseg=512)
    psds = np.zeros((N, len(freqs)), dtype=np.float32)
    for i, w in enumerate(windows_2d):
        _, psds[i] = welch(w, fs=fs, nperseg=512)

    total_power = np.trapz(psds, freqs, axis=1) + 1e-10   # (N,)

    band_feats = []
    for lo, hi in _BP_BANDS:
        idx = (freqs >= lo) & (freqs <= hi)
        bp  = np.trapz(psds[:, idx], freqs[idx], axis=1)
        band_feats.append(bp / total_power)
    band_feats = np.stack(band_feats, axis=1)              # (N, 5)

    dom_freq_idx = np.argmax(psds, axis=1)
    dom_freq     = freqs[dom_freq_idx]                     # (N,)

    psd_mean = psds.mean(axis=1)
    psd_std  = psds.std(axis=1)
    psd_max  = psds.max(axis=1)

    # --- Time domain (wektorowo) ---
    td_mean = windows_2d.mean(axis=1)
    td_std  = windows_2d.std(axis=1)
    td_rms  = np.sqrt((windows_2d**2).mean(axis=1))

    # skewness i kurtosis — scipy obsługuje axis
    td_skew = skew(windows_2d, axis=1)
    td_kurt = kurt(windows_2d, axis=1)

    signs   = np.sign(windows_2d)
    zcr     = (np.diff(signs, axis=1) != 0).sum(axis=1) / WINDOW_LEN

    # --- Składanie wektora ---
    features = np.concatenate([
        band_feats,                          # 5
        psd_mean[:,None], psd_std[:,None],   # 2
        psd_max[:,None], dom_freq[:,None],   # 2
        mag60,                               # 60
        phase60,                             # 60
        td_mean[:,None], td_std[:,None],     # 2
        td_skew[:,None], td_kurt[:,None],    # 2
        td_rms[:,None],  zcr[:,None],        # 2
    ], axis=1)                               # = 135 cech

    return features.astype(np.float32)


# =========================
# 3. PRZETWARZANIE REKORDU — I/O + segmentacja + labeling
# =========================
def process_one_record(rec_name, db, forced_label=None):
    """
    Wczytuje 1 rekord, segmentuje, etykietuje, liczy cechy batch.
    Zwraca (features_array, labels_list, rec_name) lub None przy błędzie.
    """
    rec_path = os.path.join(DATA_DIR, rec_name)

    try:
        rec = wfdb.rdrecord(rec_path)
    except Exception as e:
        return None

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))

    # Bandpass
    try:
        nyq = 0.5 * FS
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig  = filtfilt(b, a, sig)
    except:
        pass

    # Annotacje
    ann = None
    if forced_label is None:
        try:
            ann = wfdb.rdann(rec_path, 'atr')
        except:
            pass

    # Segmentacja — zbierz okna jako macierz
    starts    = np.arange(0, len(sig) - WINDOW_LEN + 1, STEP_LEN)
    windows   = np.stack([sig[s:s+WINDOW_LEN] for s in starts]).astype(np.float32)

    # Etykiety
    if forced_label is not None:
        labels = [forced_label] * len(starts)
    elif ann is not None:
        labels = []
        ann_samples = np.array(ann.sample)
        ann_symbols = np.array(ann.symbol)
        for s in starts:
            mask = (ann_samples >= s) & (ann_samples < s + WINDOW_LEN)
            syms = ann_symbols[mask].tolist()
            valid = [x for x in syms if x in ARR_SYMBOLS | NSR_SYMBOLS]
            if not valid:
                labels.append(None)
                continue
            arr_count = sum(1 for x in valid if x in ARR_SYMBOLS)
            labels.append('ARR' if arr_count >= 1 else 'NSR')
    else:
        return None

    # Filtruj okna bez etykiety
    keep    = [i for i, l in enumerate(labels) if l is not None]
    if not keep:
        return None
    windows = windows[keep]
    labels  = [labels[i] for i in keep]

    # Batch feature extraction
    features = extract_features_batch(windows)

    return features, labels, rec_name


# =========================
# 4. RÓWNOLEGŁE PRZETWARZANIE REKORDÓW
# =========================
from concurrent.futures import ProcessPoolExecutor
import functools

def run_parallel(record_db_label_list, n_workers=N_WORKERS):
    """
    record_db_label_list: [(rec_name, db, forced_label), ...]
    Zwraca all_samples: [(feat_vec, label, rec_name), ...]
    """
    all_samples = []

    # ThreadPoolExecutor — GIL nie blokuje bo większość czasu to I/O + numpy (C)
    with ThreadPoolExecutor(max_workers=n_workers) as ex:
        futures = {
            ex.submit(process_one_record, rec, db, fl): (rec, db, fl)
            for rec, db, fl in record_db_label_list
        }
        for fut in as_completed(futures):
            rec_name = futures[fut][0]
            result   = fut.result()
            if result is None:
                print(f'  SKIP {rec_name}')
                continue
            feats, labels, rname = result
            for f, l in zip(feats, labels):
                all_samples.append((f, l, rname))
            c = Counter(labels)
            print(f'  {rec_name}: {len(labels)} okien | {dict(c)}')

    return all_samples


# =========================
# 5. BUDOWA DATASETU
# =========================
NSR_RECORDS = wfdb.get_record_list('nsrdb')
CHF_RECORDS = wfdb.get_record_list('chfdb')

task_list = []
for r in MITDB_ARR_RECORDS: task_list.append((r, 'mitdb', None))
for r in MITDB_NSR_RECORDS: task_list.append((r, 'mitdb', None))
for r in NSR_RECORDS[:15]:  task_list.append((r, 'nsrdb', 'NSR'))
for r in CHF_RECORDS[:15]:  task_list.append((r, 'chfdb', 'CHF'))

print(f'\n=== PRZETWARZANIE {len(task_list)} rekordów ({N_WORKERS} wątków) ===\n')
import time
t0 = time.time()
all_samples = run_parallel(task_list, n_workers=N_WORKERS)
print(f'\nCzas: {time.time()-t0:.1f}s')

# Statystyki
lc = Counter(l for _,l,_ in all_samples)
print(f'\nŁącznie: {len(all_samples)} okien')
for cls in ['ARR','NSR','CHF']:
    n = lc.get(cls, 0)
    print(f'  {cls}: {n} ({n/len(all_samples)*100:.1f}%)')


# =========================
# 6. BALANSOWANIE + CACHE NA DYSK
# =========================
random.seed(42)
arr_s = [(f,l,r) for f,l,r in all_samples if l=='ARR']
nsr_s = [(f,l,r) for f,l,r in all_samples if l=='NSR']
chf_s = [(f,l,r) for f,l,r in all_samples if l=='CHF']

target = max(len(arr_s), len(chf_s))
nsr_s  = random.sample(nsr_s, min(len(nsr_s), target))

all_balanced = arr_s + nsr_s + chf_s
random.shuffle(all_balanced)

lc2 = Counter(l for _,l,_ in all_balanced)
print(f'\nPo balansowaniu: ARR={lc2["ARR"]} NSR={lc2["NSR"]} CHF={lc2["CHF"]}')

# Zapisz na Drive — kolejny run zacznie od razu od treningu
cache_path = os.path.join(DATA_DIR, 'dataset_cache.npz')
X_cache = np.array([s[0] for s in all_balanced])
y_cache = np.array([s[1] for s in all_balanced])
g_cache = np.array([s[2] for s in all_balanced])
np.savez_compressed(cache_path, X=X_cache, y=y_cache, groups=g_cache)
print(f'Cache zapisany: {cache_path}')

# Wczytanie cache w kolejnych runach (zamiast całego przetwarzania):
# data = np.load(cache_path, allow_pickle=True)
# X_cache, y_cache, g_cache = data['X'], data['y'], data['groups']

# =========================
# SZYBKI PIPELINE — PARALLEL + VECTORIZED
# =========================
import os, wfdb, numpy as np, torch
from scipy.signal import welch, butter, filtfilt
from scipy.fft import fft
from scipy.stats import skew, kurtosis as kurt
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
import random, warnings
warnings.filterwarnings('ignore')

FS         = 360
WINDOW_LEN = FS * 10
STEP_LEN   = FS * 5
DATA_DIR   = '/content/drive/MyDrive/ecg_data'
N_WORKERS  = 8   # wątki I/O — zwiększ do 16 jeśli Colab Pro

ARR_SYMBOLS = frozenset(['V','F','f','A','a','J','S','E','j','n','e','Q','!'])
NSR_SYMBOLS = frozenset(['N','L','R','B','/'])

MITDB_ARR_RECORDS = [
    '200','201','202','203','205','207','208','209','210',
    '212','213','214','215','217','219','220','221','222',
    '223','228','230','231','232','233','234'
]
MITDB_NSR_RECORDS = [
    '100','101','103','105','106','108','112','113',
    '114','115','116','117','118','119'
]

# =========================
# 1. BATCH DOWNLOAD — najpierw wszystko ściągnij
# =========================
def download_if_missing(rec_name, db):
    dat = os.path.join(DATA_DIR, rec_name + '.dat')
    hea = os.path.join(DATA_DIR, rec_name + '.hea')
    if os.path.exists(dat) and os.path.exists(hea):
        return True
    try:
        wfdb.dl_database(db, DATA_DIR, records=[rec_name])
        return True
    except:
        return False

def batch_download(records, db):
    print(f'  Pobieranie {len(records)} rekordów ({db})...')
    with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:
        futures = {ex.submit(download_if_missing, r, db): r for r in records}
        ok = sum(1 for f in as_completed(futures) if f.result())
    print(f'  OK: {ok}/{len(records)}')

print('=== BATCH DOWNLOAD ===')
batch_download(MITDB_ARR_RECORDS, 'mitdb')
batch_download(MITDB_NSR_RECORDS, 'mitdb')
batch_download(wfdb.get_record_list('nsrdb')[:15], 'nsrdb')
batch_download(wfdb.get_record_list('chfdb')[:15], 'chfdb')


# =========================
# 2. VECTORIZED FEATURE EXTRACTION
#    Wszystkie okna jednego rekordu naraz — bez pętli Python
# =========================
_BP_BANDS = [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15),(15,40)]

def extract_features_batch(windows_2d, fs=FS):
    """
    windows_2d: (N, WINDOW_LEN) float32
    Zwraca:    (N, n_features) float32
    Wszystkie operacje zwektoryzowane po osi 0.
    """
    N = len(windows_2d)

    # --- FFT (wszystkie okna naraz) ---
    fft_vals  = np.fft.rfft(windows_2d, axis=1)          # (N, WINDOW_LEN//2+1)
    mag_full  = np.abs(fft_vals)                          # (N, WINDOW_LEN//2+1)
    mag60     = mag_full[:, :60]
    mag60    /= (mag60.max(axis=1, keepdims=True) + 1e-10)
    phase60   = np.angle(fft_vals[:, :60])

    # --- Welch PSD (batch przez pętlę — welch nie jest wektorowy, ale liczymy raz) ---
    freqs, _ = welch(windows_2d[0], fs=fs, nperseg=512)
    psds = np.zeros((N, len(freqs)), dtype=np.float32)
    for i, w in enumerate(windows_2d):
        _, psds[i] = welch(w, fs=fs, nperseg=512)

    total_power = np.trapz(psds, freqs, axis=1) + 1e-10   # (N,)

    band_feats = []
    for lo, hi in _BP_BANDS:
        idx = (freqs >= lo) & (freqs <= hi)
        bp  = np.trapz(psds[:, idx], freqs[idx], axis=1)
        band_feats.append(bp / total_power)
    band_feats = np.stack(band_feats, axis=1)              # (N, 5)

    dom_freq_idx = np.argmax(psds, axis=1)
    dom_freq     = freqs[dom_freq_idx]                     # (N,)

    psd_mean = psds.mean(axis=1)
    psd_std  = psds.std(axis=1)
    psd_max  = psds.max(axis=1)

    # --- Time domain (wektorowo) ---
    td_mean = windows_2d.mean(axis=1)
    td_std  = windows_2d.std(axis=1)
    td_rms  = np.sqrt((windows_2d**2).mean(axis=1))

    # skewness i kurtosis — scipy obsługuje axis
    td_skew = skew(windows_2d, axis=1)
    td_kurt = kurt(windows_2d, axis=1)

    signs   = np.sign(windows_2d)
    zcr     = (np.diff(signs, axis=1) != 0).sum(axis=1) / WINDOW_LEN

    # --- Składanie wektora ---
    features = np.concatenate([
        band_feats,                          # 5
        psd_mean[:,None], psd_std[:,None],   # 2
        psd_max[:,None], dom_freq[:,None],   # 2
        mag60,                               # 60
        phase60,                             # 60
        td_mean[:,None], td_std[:,None],     # 2
        td_skew[:,None], td_kurt[:,None],    # 2
        td_rms[:,None],  zcr[:,None],        # 2
    ], axis=1)                               # = 135 cech

    return features.astype(np.float32)


# =========================
# 3. PRZETWARZANIE REKORDU — I/O + segmentacja + labeling
# =========================
def process_one_record(rec_name, db, forced_label=None):
    """
    Wczytuje 1 rekord, segmentuje, etykietuje, liczy cechy batch.
    Zwraca (features_array, labels_list, rec_name) lub None przy błędzie.
    """
    rec_path = os.path.join(DATA_DIR, rec_name)

    try:
        rec = wfdb.rdrecord(rec_path)
    except Exception as e:
        return None

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))

    # Bandpass
    try:
        nyq = 0.5 * FS
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig  = filtfilt(b, a, sig)
    except:
        pass

    # Annotacje
    ann = None
    if forced_label is None:
        try:
            ann = wfdb.rdann(rec_path, 'atr')
        except:
            pass

    # Segmentacja — zbierz okna jako macierz
    starts    = np.arange(0, len(sig) - WINDOW_LEN + 1, STEP_LEN)
    windows   = np.stack([sig[s:s+WINDOW_LEN] for s in starts]).astype(np.float32)

    # Etykiety
    if forced_label is not None:
        labels = [forced_label] * len(starts)
    elif ann is not None:
        labels = []
        ann_samples = np.array(ann.sample)
        ann_symbols = np.array(ann.symbol)
        for s in starts:
            mask = (ann_samples >= s) & (ann_samples < s + WINDOW_LEN)
            syms = ann_symbols[mask].tolist()
            valid = [x for x in syms if x in ARR_SYMBOLS | NSR_SYMBOLS]
            if not valid:
                labels.append(None)
                continue
            arr_count = sum(1 for x in valid if x in ARR_SYMBOLS)
            labels.append('ARR' if arr_count >= 1 else 'NSR')
    else:
        return None

    # Filtruj okna bez etykiety
    keep    = [i for i, l in enumerate(labels) if l is not None]
    if not keep:
        return None
    windows = windows[keep]
    labels  = [labels[i] for i in keep]

    # Batch feature extraction
    features = extract_features_batch(windows)

    return features, labels, rec_name


# =========================
# 4. RÓWNOLEGŁE PRZETWARZANIE REKORDÓW
# =========================
from concurrent.futures import ProcessPoolExecutor
import functools

def run_parallel(record_db_label_list, n_workers=N_WORKERS):
    """
    record_db_label_list: [(rec_name, db, forced_label), ...]
    Zwraca all_samples: [(feat_vec, label, rec_name), ...]
    """
    all_samples = []

    # ThreadPoolExecutor — GIL nie blokuje bo większość czasu to I/O + numpy (C)
    with ThreadPoolExecutor(max_workers=n_workers) as ex:
        futures = {
            ex.submit(process_one_record, rec, db, fl): (rec, db, fl)
            for rec, db, fl in record_db_label_list
        }
        for fut in as_completed(futures):
            rec_name = futures[fut][0]
            result   = fut.result()
            if result is None:
                print(f'  SKIP {rec_name}')
                continue
            feats, labels, rname = result
            for f, l in zip(feats, labels):
                all_samples.append((f, l, rname))
            c = Counter(labels)
            print(f'  {rec_name}: {len(labels)} okien | {dict(c)}')

    return all_samples


# =========================
# 5. BUDOWA DATASETU
# =========================
NSR_RECORDS = wfdb.get_record_list('nsrdb')
CHF_RECORDS = wfdb.get_record_list('chfdb')

task_list = []
for r in MITDB_ARR_RECORDS: task_list.append((r, 'mitdb', None))
for r in MITDB_NSR_RECORDS: task_list.append((r, 'mitdb', None))
for r in NSR_RECORDS[:15]:  task_list.append((r, 'nsrdb', 'NSR'))
for r in CHF_RECORDS[:15]:  task_list.append((r, 'chfdb', 'CHF'))

print(f'\n=== PRZETWARZANIE {len(task_list)} rekordów ({N_WORKERS} wątków) ===\n')
import time
t0 = time.time()
all_samples = run_parallel(task_list, n_workers=N_WORKERS)
print(f'\nCzas: {time.time()-t0:.1f}s')

# Statystyki
lc = Counter(l for _,l,_ in all_samples)
print(f'\nŁącznie: {len(all_samples)} okien')
for cls in ['ARR','NSR','CHF']:
    n = lc.get(cls, 0)
    print(f'  {cls}: {n} ({n/len(all_samples)*100:.1f}%)')


# =========================
# 6. BALANSOWANIE + CACHE NA DYSK
# =========================
random.seed(42)
arr_s = [(f,l,r) for f,l,r in all_samples if l=='ARR']
nsr_s = [(f,l,r) for f,l,r in all_samples if l=='NSR']
chf_s = [(f,l,r) for f,l,r in all_samples if l=='CHF']

target = max(len(arr_s), len(chf_s))
nsr_s  = random.sample(nsr_s, min(len(nsr_s), target))

all_balanced = arr_s + nsr_s + chf_s
random.shuffle(all_balanced)

lc2 = Counter(l for _,l,_ in all_balanced)
print(f'\nPo balansowaniu: ARR={lc2["ARR"]} NSR={lc2["NSR"]} CHF={lc2["CHF"]}')

# Zapisz na Drive — kolejny run zacznie od razu od treningu
cache_path = os.path.join(DATA_DIR, 'dataset_cache.npz')
X_cache = np.array([s[0] for s in all_balanced])
y_cache = np.array([s[1] for s in all_balanced])
g_cache = np.array([s[2] for s in all_balanced])
np.savez_compressed(cache_path, X=X_cache, y=y_cache, groups=g_cache)
print(f'Cache zapisany: {cache_path}')

# Wczytanie cache w kolejnych runach (zamiast całego przetwarzania):
# data = np.load(cache_path, allow_pickle=True)
# X_cache, y_cache, g_cache = data['X'], data['y'], data['groups']

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X_cache, y_cache, g_cache))

X_train, X_test = X_cache[train_idx], X_cache[test_idx]
y_train, y_test = y_cache[train_idx], y_cache[test_idx]

print(f'\nTrain: {len(X_train)} | Test: {len(X_test)}')
print(f'Train rekordy: {len(set(g_cache[train_idx]))} | '
      f'Test rekordy: {len(set(g_cache[test_idx]))}')
print(f'Train: {dict(Counter(y_train))}')
print(f'Test:  {dict(Counter(y_test))}')

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)
print(f'Klasy: {list(le.classes_)}')

scaler      = StandardScaler()
X_train_sc  = scaler.fit_transform(X_train)
X_test_sc   = scaler.transform(X_test)


# =========================
# 8. CLASS WEIGHTS
# =========================
cw = compute_class_weight('balanced',
                          classes=np.unique(y_train_enc),
                          y=y_train_enc)
class_weights = torch.tensor(cw, dtype=torch.float32).to(DEVICE)
print(f'Class weights: {dict(zip(le.classes_, cw.round(3)))}')


# =========================
# 9. MODEL
# =========================
class WindowCNN(nn.Module):
    def __init__(self, input_dim, n_classes):
        super().__init__()
        self.input_bn = nn.BatchNorm1d(1)

        self.block1 = nn.Sequential(
            nn.Conv1d(1, 64, kernel_size=7, padding=3),
            nn.BatchNorm1d(64), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(64, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64), nn.GELU(),
        )
        self.pool1 = nn.MaxPool1d(2)

        self.block2 = nn.Sequential(
            nn.Conv1d(64, 128, kernel_size=5, padding=2),
            nn.BatchNorm1d(128), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128), nn.GELU(),
        )
        self.pool2 = nn.MaxPool1d(2)

        self.block3 = nn.Sequential(
            nn.Conv1d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm1d(256), nn.GELU(), nn.Dropout(0.3),
        )
        self.gap = nn.AdaptiveAvgPool1d(1)

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.4),
            nn.Linear(128, 64),  nn.GELU(),
            nn.Linear(64, n_classes),
        )

    def forward(self, x):
        x = x.unsqueeze(1)
        x = self.input_bn(x)
        x = self.pool1(self.block1(x))
        x = self.pool2(self.block2(x))
        x = self.gap(self.block3(x))
        return self.fc(x)


# =========================
# 10. TRENING
# =========================
X_tr_t = torch.tensor(X_train_sc, dtype=torch.float32)
y_tr_t = torch.tensor(y_train_enc, dtype=torch.long)
X_te_t = torch.tensor(X_test_sc,  dtype=torch.float32)
y_te_t = torch.tensor(y_test_enc,  dtype=torch.long)

train_dl = DataLoader(TensorDataset(X_tr_t, y_tr_t),
                      batch_size=64, shuffle=True, drop_last=True)
test_dl  = DataLoader(TensorDataset(X_te_t, y_te_t),
                      batch_size=128, shuffle=False)

n_classes = len(le.classes_)
model     = WindowCNN(X_train_sc.shape[1], n_classes).to(DEVICE)
print(f'\nParametry CNN: {sum(p.numel() for p in model.parameters()):,}')
print(f'Input dim: {X_train_sc.shape[1]}')

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-3)
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=1e-3, epochs=80,
    steps_per_epoch=len(train_dl), pct_start=0.2
)

EPOCHS       = 80
PATIENCE     = 12
best_f1      = 0.0
patience_cnt = 0
best_state   = None
history      = {'tl':[],'ta':[],'vl':[],'va':[],'vf':[]}

print(f'\nTrening (max {EPOCHS} epok, patience={PATIENCE})...\n')

for epoch in range(EPOCHS):
    # -- train --
    model.train()
    tl, tc, tt = 0., 0, 0
    for xb, yb in train_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        logits = model(xb)
        loss   = criterion(logits, yb)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        tl += loss.item() * len(xb)
        tc += (logits.argmax(1) == yb).sum().item()
        tt += len(xb)

    # -- val --
    model.eval()
    vl, vc, vt, vp, vg = 0., 0, 0, [], []
    with torch.no_grad():
        for xb, yb in test_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            logits = model(xb)
            vl    += criterion(logits, yb).item() * len(xb)
            preds  = logits.argmax(1)
            vc    += (preds == yb).sum().item()
            vt    += len(xb)
            vp.extend(preds.cpu().numpy())
            vg.extend(yb.cpu().numpy())

    val_f1 = f1_score(vg, vp, average='macro')
    history['tl'].append(tl/tt);  history['ta'].append(tc/tt)
    history['vl'].append(vl/vt);  history['va'].append(vc/vt)
    history['vf'].append(val_f1)

    if (epoch+1) % 5 == 0:
        print(f'Ep {epoch+1:3d} | '
              f'Loss {tl/tt:.4f}/{vl/vt:.4f} | '
              f'Acc {tc/tt*100:.1f}%/{vc/vt*100:.1f}% | '
              f'F1 {val_f1:.4f}')

    if val_f1 > best_f1:
        best_f1      = val_f1
        best_state   = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_cnt = 0
    else:
        patience_cnt += 1
        if patience_cnt >= PATIENCE:
            print(f'\nEarly stopping @ ep {epoch+1} | Best F1={best_f1:.4f}')
            break

model.load_state_dict(best_state)
print(f'Best model załadowany (F1={best_f1:.4f})')


# =========================
# 11. EWALUACJA
# =========================
model.eval()
all_preds, all_probs = [], []
with torch.no_grad():
    for xb, _ in test_dl:
        logits = model(xb.to(DEVICE))
        all_probs.extend(torch.softmax(logits, 1).cpu().numpy())
        all_preds.extend(logits.argmax(1).cpu().numpy())

y_pred = np.array(all_preds)
print('\n=== RAPORT KOŃCOWY ===')
print(f'Accuracy : {accuracy_score(y_test_enc, y_pred):.4f}')
print(f'F1-macro : {f1_score(y_test_enc, y_pred, average="macro"):.4f}')
print()
print(classification_report(y_test_enc, y_pred, target_names=le.classes_))

# Wykresy
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Krzywe uczenia
ax = axes[0]
ax.plot(history['tl'], label='train loss')
ax.plot(history['vl'], label='val loss')
ax.set_title('Loss'); ax.set_xlabel('Epoka')
ax.legend(); ax.grid(True, alpha=0.3)

ax = axes[1]
ax.plot([a*100 for a in history['ta']], label='train acc')
ax.plot([a*100 for a in history['va']], label='val acc')
ax.plot([f*100 for f in history['vf']], label='val F1', linestyle='--')
ax.set_title('Accuracy / F1'); ax.set_xlabel('Epoka'); ax.set_ylabel('%')
ax.legend(); ax.grid(True, alpha=0.3)

# Macierz konfuzji
ax  = axes[2]
cm  = confusion_matrix(y_test_enc, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_, ax=ax)
ax.set_xlabel('Predykcja'); ax.set_ylabel('Ground Truth')
ax.set_title('Macierz konfuzji (window-level)')

plt.tight_layout()
plt.savefig(os.path.join(DATA_DIR, 'results.png'), dpi=120, bbox_inches='tight')
plt.show()


# =========================
# 12. ZAPIS MODELU
# =========================
torch.save({
    'model_state': model.state_dict(),
    'scaler':      scaler,
    'le':          le,
    'input_dim':   X_train_sc.shape[1],
    'n_classes':   n_classes,
    'best_f1':     best_f1,
}, MODEL_PATH)
print(f'Model zapisany: {MODEL_PATH}')


# =========================
# 13. SLIDING WINDOW INFERENCE — PRZYKŁAD
# =========================
def infer_record(rec_name, db, model, scaler, le):
    rec_path = os.path.join(DATA_DIR, rec_name)
    try:
        rec = wfdb.rdrecord(rec_path)
    except:
        rec = wfdb.rdrecord(rec_name, pn_dir=db)

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))
    try:
        nyq  = 0.5 * FS
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig  = filtfilt(b, a, sig)
    except:
        pass

    ann = None
    try:
        ann = wfdb.rdann(rec_path, 'atr')
    except:
        pass

    starts   = np.arange(0, len(sig) - WINDOW_LEN + 1, STEP_LEN)
    windows  = np.stack([sig[s:s+WINDOW_LEN] for s in starts]).astype(np.float32)
    feats    = extract_features_batch(windows)
    feats_sc = scaler.transform(feats)

    model.eval()
    with torch.no_grad():
        logits = model(torch.tensor(feats_sc).to(DEVICE))
        probs  = torch.softmax(logits, 1).cpu().numpy()
        preds  = logits.argmax(1).cpu().numpy()

    results = []
    for i, (s, pred_idx) in enumerate(zip(starts, preds)):
        gt = None
        if ann is not None:
            mask  = (np.array(ann.sample) >= s) & (np.array(ann.sample) < s + WINDOW_LEN)
            syms  = np.array(ann.symbol)[mask].tolist()
            valid = [x for x in syms if x in ARR_SYMBOLS | NSR_SYMBOLS]
            if valid:
                arr_n = sum(1 for x in valid if x in ARR_SYMBOLS)
                gt    = 'ARR' if arr_n >= 1 else 'NSR'

        results.append({
            'start_s':    s / FS,
            'end_s':      (s + WINDOW_LEN) / FS,
            'pred':       le.classes_[pred_idx],
            'gt':         gt,
            'probs':      dict(zip(le.classes_, probs[i].round(3))),
            'correct':    (le.classes_[pred_idx] == gt) if gt else None,
        })

    return results


print('\n=== PRZYKŁAD INFERENCE: rekord 208 (ARR) ===')
results = infer_record('208', 'mitdb', model, scaler, le)

correct = sum(1 for r in results if r['correct'] is True)
total   = sum(1 for r in results if r['correct'] is not None)
print(f'Accuracy na rekordzie: {correct}/{total} ({correct/total*100:.1f}%)\n')

print(f'{"Start":>7} {"Koniec":>7} | {"Pred":>4} | {"GT":>4} | {"OK":>3} | Prawdopodobieństwa')
print('-' * 72)
for r in results[:25]:
    ok_str = '✔' if r['correct'] else ('✘' if r['correct'] is False else '-')
    pb     = ' | '.join(f'{k}:{v:.2f}' for k,v in sorted(r['probs'].items()))
    print(f'{r["start_s"]:>6.1f}s {r["end_s"]:>6.1f}s | '
          f'{r["pred"]:>4} | {str(r["gt"]):>4} | {ok_str:>3} | {pb}')

# ============================================================
# ECG — WINDOW-LEVEL DETECTION — PEŁNY PIPELINE
# ============================================================

# =========================
# 0. INSTALACJA
# =========================
!pip install wfdb scikit-learn imbalanced-learn scipy torch seaborn matplotlib numpy -q

import os, random, time, warnings
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
import wfdb

from scipy.signal import welch, butter, filtfilt
from scipy.stats import skew, kurtosis as kurt
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (classification_report, confusion_matrix,
                             accuracy_score, f1_score)
from sklearn.utils.class_weight import compute_class_weight
from torch.utils.data import DataLoader, TensorDataset

warnings.filterwarnings('ignore')
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'PyTorch: {torch.__version__} | Device: {DEVICE}')


# =========================
# 1. KONFIGURACJA
# =========================
from google.colab import drive
drive.mount('/content/drive')

DATA_DIR   = '/content/drive/MyDrive/ecg_data'
MODEL_PATH = os.path.join(DATA_DIR, 'window_cnn_balanced.pt')
os.makedirs(DATA_DIR, exist_ok=True)

FS         = 360
WINDOW_LEN = FS * 10
STEP_LEN   = FS * 5
N_WORKERS  = 8

ARR_SYMBOLS = frozenset(['V','F','f','A','a','J','S','E','j','n','e','Q','!'])
NSR_SYMBOLS = frozenset(['N','L','R','B','/'])

MITDB_ARR_RECORDS = [
    '200','201','202','203','205','207','208','209','210',
    '212','213','214','215','217','219','220','221','222',
    '223','228','230','231','232','233','234'
]
MITDB_NSR_RECORDS = [
    '100','101','103','105','106','108','112','113',
    '114','115','116','117','118','119'
]
NSR_RECORDS = wfdb.get_record_list('nsrdb')[:15]
CHF_RECORDS = wfdb.get_record_list('chfdb')[:15]


# =========================
# 2. FEATURE EXTRACTION (batch)
# =========================
_BP_BANDS = [(0.04,0.15),(0.15,0.4),(0.5,5),(5,15),(15,40)]

def extract_features_batch(windows_2d, fs=FS):
    N = len(windows_2d)

    fft_c   = np.fft.rfft(windows_2d, axis=1)
    mag_all = np.abs(fft_c)
    mag60   = mag_all[:, :60].copy()
    mag60  /= (mag60.max(axis=1, keepdims=True) + 1e-10)
    phase60 = np.angle(fft_c[:, :60])

    freqs, _ = welch(windows_2d[0], fs=fs, nperseg=512)
    psds = np.empty((N, len(freqs)), dtype=np.float32)
    for i, w in enumerate(windows_2d):
        _, psds[i] = welch(w, fs=fs, nperseg=512)

    total_power = np.trapz(psds, freqs, axis=1) + 1e-10
    band_feats  = []
    for lo, hi in _BP_BANDS:
        idx = (freqs >= lo) & (freqs <= hi)
        bp  = np.trapz(psds[:, idx], freqs[idx], axis=1)
        band_feats.append(bp / total_power)
    band_feats = np.stack(band_feats, axis=1)

    dom_freq = freqs[np.argmax(psds, axis=1)]
    psd_mean = psds.mean(axis=1)
    psd_std  = psds.std(axis=1)
    psd_max  = psds.max(axis=1)

    td_mean = windows_2d.mean(axis=1)
    td_std  = windows_2d.std(axis=1)
    td_rms  = np.sqrt((windows_2d**2).mean(axis=1))
    td_skew = skew(windows_2d, axis=1).astype(np.float32)
    td_kurt = kurt(windows_2d, axis=1).astype(np.float32)
    zcr     = (np.diff(np.sign(windows_2d), axis=1) != 0).sum(axis=1) / WINDOW_LEN

    features = np.concatenate([
        band_feats,
        psd_mean[:,None], psd_std[:,None],
        psd_max[:,None],  dom_freq[:,None],
        mag60, phase60,
        td_mean[:,None],  td_std[:,None],
        td_skew[:,None],  td_kurt[:,None],
        td_rms[:,None],   zcr[:,None],
    ], axis=1)

    return features.astype(np.float32)


# =========================
# 3. PRZETWARZANIE REKORDU
# =========================
def process_one_record(rec_name, db, forced_label=None):
    rec_path = os.path.join(DATA_DIR, rec_name)
    try:
        rec = wfdb.rdrecord(rec_path)
    except:
        try:
            rec = wfdb.rdrecord(rec_name, pn_dir=db)
        except Exception as e:
            print(f'  ERR {rec_name}: {e}')
            return None

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))
    try:
        nyq  = 0.5 * FS
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig  = filtfilt(b, a, sig)
    except:
        pass

    ann = None
    if forced_label is None:
        try:
            ann = wfdb.rdann(rec_path, 'atr')
        except:
            try:
                ann = wfdb.rdann(rec_name, 'atr', pn_dir=db)
            except:
                pass

    starts = np.arange(0, len(sig) - WINDOW_LEN + 1, STEP_LEN)
    if len(starts) == 0:
        return None

    windows = [sig[s:s+WINDOW_LEN].astype(np.float32) for s in starts]

    if forced_label is not None:
        labels = [forced_label] * len(starts)
    elif ann is not None:
        ann_s  = np.array(ann.sample)
        ann_sy = np.array(ann.symbol)
        labels = []
        for s in starts:
            mask  = (ann_s >= s) & (ann_s < s + WINDOW_LEN)
            syms  = ann_sy[mask].tolist()
            valid = [x for x in syms if x in ARR_SYMBOLS | NSR_SYMBOLS]
            if not valid:
                labels.append(None)
                continue
            arr_n = sum(1 for x in valid if x in ARR_SYMBOLS)
            labels.append('ARR' if arr_n >= 1 else 'NSR')
    else:
        return None

    keep = [i for i, l in enumerate(labels) if l is not None]
    if not keep:
        return None

    windows_np = np.stack([windows[i] for i in keep])
    labels_f   = [labels[i] for i in keep]
    features   = extract_features_batch(windows_np)

    return features, labels_f, rec_name


# =========================
# 4. RÓWNOLEGŁE PRZETWARZANIE
# =========================
def run_parallel(task_list, n_workers=N_WORKERS):
    all_samples = []
    with ThreadPoolExecutor(max_workers=n_workers) as ex:
        futures = {
            ex.submit(process_one_record, rec, db, fl): rec
            for rec, db, fl in task_list
        }
        for fut in as_completed(futures):
            rec_name = futures[fut]
            result   = fut.result()
            if result is None:
                print(f'  SKIP {rec_name}')
                continue
            feats, labels, rname = result
            for f, l in zip(feats, labels):
                all_samples.append((f, l, rname))
            c = Counter(labels)
            print(f'  {rec_name}: {len(labels)} okien | {dict(c)}')
    return all_samples


# =========================
# 5. BUDOWA DATASETU
# =========================
print('=== PRZETWARZANIE REKORDÓW ===\n')
task_list = []
for r in MITDB_ARR_RECORDS: task_list.append((r, 'mitdb', None))
for r in MITDB_NSR_RECORDS: task_list.append((r, 'mitdb', None))
for r in NSR_RECORDS:       task_list.append((r, 'nsrdb', 'NSR'))
for r in CHF_RECORDS:       task_list.append((r, 'chfdb', 'CHF'))

t0          = time.time()
all_samples = run_parallel(task_list)
print(f'\nCzas przetwarzania: {time.time()-t0:.1f}s')

lc = Counter(l for _,l,_ in all_samples)
print(f'\nSurowe dane:')
print(f'  ARR: {lc.get("ARR", 0)}')
print(f'  NSR: {lc.get("NSR", 0)}')
print(f'  CHF: {lc.get("CHF", 0)}')


# =========================
# 6. BALANSOWANIE — ARR dyktuje rozmiar
# =========================
random.seed(42)

arr_s = [(f,l,r) for f,l,r in all_samples if l=='ARR']
nsr_s = [(f,l,r) for f,l,r in all_samples if l=='NSR']
chf_s = [(f,l,r) for f,l,r in all_samples if l=='CHF']

target = len(arr_s)
print(f'\nTarget na klasę: {target} okien')

nsr_balanced = random.choices(nsr_s, k=target) if len(nsr_s) < target \
               else random.sample(nsr_s, target)
chf_balanced = random.choices(chf_s, k=target) if len(chf_s) < target \
               else random.sample(chf_s, target)

balanced = arr_s + nsr_balanced + chf_balanced
random.shuffle(balanced)

lc2 = Counter(l for _,l,_ in balanced)
print(f'\nPo balansowaniu:')
print(f'  ARR: {lc2["ARR"]} | NSR: {lc2["NSR"]} | CHF: {lc2["CHF"]}')
print(f'  ŁĄCZNIE: {len(balanced)}')

X_all = np.array([s[0] for s in balanced])
y_all = np.array([s[1] for s in balanced])
g_all = np.array([s[2] for s in balanced])


# =========================
# 7. SPLIT PO REKORDACH
# =========================
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X_all, y_all, g_all))

X_train, X_test = X_all[train_idx], X_all[test_idx]
y_train, y_test = y_all[train_idx], y_all[test_idx]

print(f'\nTrain: {len(X_train)} | Test: {len(X_test)}')
print(f'Train rekordy: {len(set(g_all[train_idx]))} | '
      f'Test rekordy: {len(set(g_all[test_idx]))}')
print(f'Train: {dict(Counter(y_train))}')
print(f'Test:  {dict(Counter(y_test))}')

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)
print(f'Klasy: {list(le.classes_)}')

scaler     = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

cw = compute_class_weight('balanced',
                          classes=np.unique(y_train_enc),
                          y=y_train_enc)
class_weights = torch.tensor(cw, dtype=torch.float32).to(DEVICE)
print(f'Class weights: {dict(zip(le.classes_, cw.round(3)))}')


# =========================
# 8. MODEL
# =========================
class WindowCNN(nn.Module):
    def __init__(self, input_dim, n_classes):
        super().__init__()
        self.input_bn = nn.BatchNorm1d(1)
        self.block1 = nn.Sequential(
            nn.Conv1d(1, 64, kernel_size=7, padding=3),
            nn.BatchNorm1d(64), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(64, 64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64), nn.GELU(),
        )
        self.pool1 = nn.MaxPool1d(2)
        self.block2 = nn.Sequential(
            nn.Conv1d(64, 128, kernel_size=5, padding=2),
            nn.BatchNorm1d(128), nn.GELU(), nn.Dropout(0.2),
            nn.Conv1d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128), nn.GELU(),
        )
        self.pool2 = nn.MaxPool1d(2)
        self.block3 = nn.Sequential(
            nn.Conv1d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm1d(256), nn.GELU(), nn.Dropout(0.3),
        )
        self.gap = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.4),
            nn.Linear(128, 64),  nn.GELU(),
            nn.Linear(64, n_classes),
        )

    def forward(self, x):
        x = x.unsqueeze(1)
        x = self.input_bn(x)
        x = self.pool1(self.block1(x))
        x = self.pool2(self.block2(x))
        x = self.gap(self.block3(x))
        return self.fc(x)


# =========================
# 9. TRENING
# =========================
X_tr_t = torch.tensor(X_train_sc, dtype=torch.float32)
y_tr_t = torch.tensor(y_train_enc, dtype=torch.long)
X_te_t = torch.tensor(X_test_sc,  dtype=torch.float32)
y_te_t = torch.tensor(y_test_enc,  dtype=torch.long)

train_dl = DataLoader(TensorDataset(X_tr_t, y_tr_t),
                      batch_size=64, shuffle=True, drop_last=True)
test_dl  = DataLoader(TensorDataset(X_te_t, y_te_t),
                      batch_size=128, shuffle=False)

n_classes = len(le.classes_)
model     = WindowCNN(X_train_sc.shape[1], n_classes).to(DEVICE)
print(f'\nParametry CNN: {sum(p.numel() for p in model.parameters()):,}')
print(f'Input dim: {X_train_sc.shape[1]}')

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-3)
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=1e-3, epochs=80,
    steps_per_epoch=len(train_dl), pct_start=0.2
)

EPOCHS       = 80
PATIENCE     = 12
best_f1      = 0.0
patience_cnt = 0
best_state   = None
history      = {'tl':[],'ta':[],'vl':[],'va':[],'vf':[]}

print(f'Trening (max {EPOCHS} epok, patience={PATIENCE})...\n')

for epoch in range(EPOCHS):
    model.train()
    tl, tc, tt = 0., 0, 0
    for xb, yb in train_dl:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        optimizer.zero_grad()
        logits = model(xb)
        loss   = criterion(logits, yb)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        tl += loss.item() * len(xb)
        tc += (logits.argmax(1) == yb).sum().item()
        tt += len(xb)

    model.eval()
    vl, vc, vt, vp, vg = 0., 0, 0, [], []
    with torch.no_grad():
        for xb, yb in test_dl:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            logits = model(xb)
            vl    += criterion(logits, yb).item() * len(xb)
            preds  = logits.argmax(1)
            vc    += (preds == yb).sum().item()
            vt    += len(xb)
            vp.extend(preds.cpu().numpy())
            vg.extend(yb.cpu().numpy())

    val_f1 = f1_score(vg, vp, average='macro')
    history['tl'].append(tl/tt);  history['ta'].append(tc/tt)
    history['vl'].append(vl/vt);  history['va'].append(vc/vt)
    history['vf'].append(val_f1)

    if (epoch+1) % 5 == 0:
        print(f'Ep {epoch+1:3d} | '
              f'Loss {tl/tt:.4f}/{vl/vt:.4f} | '
              f'Acc {tc/tt*100:.1f}%/{vc/vt*100:.1f}% | '
              f'F1 {val_f1:.4f}')

    if val_f1 > best_f1:
        best_f1      = val_f1
        best_state   = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        patience_cnt = 0
    else:
        patience_cnt += 1
        if patience_cnt >= PATIENCE:
            print(f'\nEarly stopping @ ep {epoch+1} | Best F1={best_f1:.4f}')
            break

model.load_state_dict(best_state)
print(f'Best model załadowany (F1={best_f1:.4f})')


# =========================
# 10. EWALUACJA
# =========================
model.eval()
all_preds, all_probs = [], []
with torch.no_grad():
    for xb, _ in test_dl:
        logits = model(xb.to(DEVICE))
        all_probs.extend(torch.softmax(logits, 1).cpu().numpy())
        all_preds.extend(logits.argmax(1).cpu().numpy())

y_pred = np.array(all_preds)
print('\n=== RAPORT KOŃCOWY ===')
print(f'Accuracy : {accuracy_score(y_test_enc, y_pred):.4f}')
print(f'F1-macro : {f1_score(y_test_enc, y_pred, average="macro"):.4f}')
print()
print(classification_report(y_test_enc, y_pred, target_names=le.classes_))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

ax = axes[0]
ax.plot(history['tl'], label='train loss')
ax.plot(history['vl'], label='val loss')
ax.set_title('Loss'); ax.legend(); ax.grid(True, alpha=0.3)

ax = axes[1]
ax.plot([a*100 for a in history['ta']], label='train acc')
ax.plot([a*100 for a in history['va']], label='val acc')
ax.plot([f*100 for f in history['vf']], label='val F1', linestyle='--')
ax.set_title('Accuracy / F1'); ax.set_ylabel('%')
ax.legend(); ax.grid(True, alpha=0.3)

ax = axes[2]
cm = confusion_matrix(y_test_enc, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_, ax=ax)
ax.set_xlabel('Predykcja'); ax.set_ylabel('Ground Truth')
ax.set_title('Macierz konfuzji')

plt.tight_layout()
plt.savefig(os.path.join(DATA_DIR, 'results_balanced.png'), dpi=120, bbox_inches='tight')
plt.show()


# =========================
# 11. ZAPIS MODELU
# =========================
torch.save({
    'model_state': model.state_dict(),
    'scaler':      scaler,
    'le':          le,
    'input_dim':   X_train_sc.shape[1],
    'n_classes':   n_classes,
    'best_f1':     best_f1,
}, MODEL_PATH)
print(f'Model zapisany: {MODEL_PATH}')


# =========================
# 12. PRZYKŁAD SLIDING WINDOW INFERENCE
# =========================
def infer_record(rec_name, db, model, scaler, le):
    rec_path = os.path.join(DATA_DIR, rec_name)
    try:
        rec = wfdb.rdrecord(rec_path)
    except:
        rec = wfdb.rdrecord(rec_name, pn_dir=db)

    sig = np.nan_to_num(rec.p_signal[:, 0].astype(np.float64))
    try:
        nyq  = 0.5 * FS
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig  = filtfilt(b, a, sig)
    except:
        pass

    ann = None
    try:
        ann = wfdb.rdann(rec_path, 'atr')
    except:
        pass

    starts   = np.arange(0, len(sig) - WINDOW_LEN + 1, STEP_LEN)
    windows  = np.stack([sig[s:s+WINDOW_LEN] for s in starts]).astype(np.float32)
    feats_sc = scaler.transform(extract_features_batch(windows))

    model.eval()
    with torch.no_grad():
        logits = model(torch.tensor(feats_sc).to(DEVICE))
        probs  = torch.softmax(logits, 1).cpu().numpy()
        preds  = logits.argmax(1).cpu().numpy()

    results = []
    for i, (s, pred_idx) in enumerate(zip(starts, preds)):
        gt = None
        if ann is not None:
            ann_s  = np.array(ann.sample)
            ann_sy = np.array(ann.symbol)
            mask   = (ann_s >= s) & (ann_s < s + WINDOW_LEN)
            syms   = ann_sy[mask].tolist()
            valid  = [x for x in syms if x in ARR_SYMBOLS | NSR_SYMBOLS]
            if valid:
                arr_n = sum(1 for x in valid if x in ARR_SYMBOLS)
                gt    = 'ARR' if arr_n >= 1 else 'NSR'

        pred_label = le.classes_[pred_idx]
        results.append({
            'start_s': s / FS,
            'end_s':   (s + WINDOW_LEN) / FS,
            'pred':    pred_label,
            'gt':      gt,
            'probs':   dict(zip(le.classes_, probs[i].round(3))),
            'correct': (pred_label == gt) if gt else None,
        })

    return results

print('\n=== PRZYKŁAD INFERENCE: rekord 208 (ARR) ===')
results = infer_record('208', 'mitdb', model, scaler, le)
correct = sum(1 for r in results if r['correct'] is True)
total   = sum(1 for r in results if r['correct'] is not None)
print(f'Accuracy na rekordzie: {correct}/{total} ({correct/total*100:.1f}%)\n')

print(f'{"Start":>7} {"Koniec":>7} | {"Pred":>4} | {"GT":>4} | {"OK":>3} | Prawdopodobieństwa')
print('-' * 75)
for r in results[:25]:
    ok  = '✔' if r['correct'] else ('✘' if r['correct'] is False else '-')
    pb  = ' | '.join(f'{k}:{v:.2f}' for k,v in sorted(r['probs'].items()))
    print(f'{r["start_s"]:>6.1f}s {r["end_s"]:>6.1f}s | '
          f'{r["pred"]:>4} | {str(r["gt"]):>4} | {ok:>3} | {pb}')

# =========================
# 11. ZAPIS MODELU
# =========================
import json, pickle

DATA_DIR  = '/content/drive/MyDrive/ecg_data'
MODEL_DIR = os.path.join(DATA_DIR, 'model')
os.makedirs(MODEL_DIR, exist_ok=True)

WEIGHTS_PATH = os.path.join(MODEL_DIR, 'window_cnn_balanced_weights.pt')
SKLEARN_PATH = os.path.join(MODEL_DIR, 'window_cnn_balanced_sklearn.pkl')
META_PATH    = os.path.join(MODEL_DIR, 'window_cnn_balanced_meta.json')

# 1) Wagi PyTorch
torch.save({
    'model_state': model.state_dict(),
    'model_config': {
        'input_dim': X_train_sc.shape[1],
        'n_classes': n_classes,
    },
    'best_f1': best_f1,
}, WEIGHTS_PATH)

# 2) Obiekty sklearn osobno
with open(SKLEARN_PATH, 'wb') as f:
    pickle.dump({'scaler': scaler, 'le': le}, f)

# 3) Metadata JSON
with open(META_PATH, 'w') as f:
    json.dump({
        'input_dim':  X_train_sc.shape[1],
        'n_classes':  n_classes,
        'classes':    list(le.classes_),
        'best_f1':    round(best_f1, 4),
        'fs':         FS,
        'window_len': WINDOW_LEN,
        'step_len':   STEP_LEN,
    }, f, indent=2)

print(f'Wagi:    {WEIGHTS_PATH}')
print(f'Sklearn: {SKLEARN_PATH}')
print(f'Meta:    {META_PATH}')


# =========================
# 12. FUNKCJE DO UŻYCIA W APLIKACJI
# =========================

def load_model(weights_path, device=None):
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    ckpt = torch.load(weights_path, map_location=device, weights_only=True)

    sklearn_path = weights_path.replace('_weights.pt', '_sklearn.pkl')
    with open(sklearn_path, 'rb') as f:
        sk = pickle.load(f)

    meta_path = weights_path.replace('_weights.pt', '_meta.json')
    with open(meta_path) as f:
        meta = json.load(f)

    net = WindowCNN(
        input_dim=ckpt['model_config']['input_dim'],
        n_classes=ckpt['model_config']['n_classes'],
    ).to(device)
    net.load_state_dict(ckpt['model_state'])
    net.eval()

    return {
        'net':        net,
        'scaler':     sk['scaler'],
        'le':         sk['le'],
        'device':     device,
        'fs':         meta['fs'],
        'window_len': meta['window_len'],
        'step_len':   meta['step_len'],
        'classes':    meta['classes'],
    }


def predict_signal(signal_1d, model_dict, return_windows=False):
    md = model_dict
    sig = np.nan_to_num(signal_1d.astype(np.float64))

    try:
        nyq = 0.5 * md['fs']
        b, a = butter(4, [0.5/nyq, 40.0/nyq], btype='band')
        sig = filtfilt(b, a, sig)
    except Exception:
        pass

    starts = np.arange(0, len(sig) - md['window_len'] + 1, md['step_len'])
    if len(starts) == 0:
        raise ValueError(
            f'Sygnał za krótki – potrzeba min {md["window_len"]} próbek '
            f'({md["window_len"]/md["fs"]:.1f}s przy fs={md["fs"]}Hz)'
        )

    windows = np.stack([sig[s:s+md['window_len']] for s in starts]).astype(np.float32)
    feats = extract_features_batch(windows, fs=md['fs'])
    feats_sc = md['scaler'].transform(feats)

    with torch.no_grad():
        logits = md['net'](torch.tensor(feats_sc).to(md['device']))
        probs = torch.softmax(logits, 1).cpu().numpy()
        preds = logits.argmax(1).cpu().numpy()

    pred_labels = md['le'].inverse_transform(preds)
    counts = Counter(pred_labels)
    total = len(pred_labels)
    majority = counts.most_common(1)[0][0]
    maj_idx = md['le'].transform([majority])[0]
    maj_prob = float(probs[preds == maj_idx, maj_idx].mean()) if (preds == maj_idx).any() else 0.0

    result = {
        'majority_class': majority,
        'majority_prob': round(maj_prob, 3),
        'class_distribution': {k: round(v/total*100, 1) for k, v in counts.items()},
        'n_windows': total,
    }

    if return_windows:
        result['window_results'] = [
            {
                'start_s': float(s / md['fs']),
                'end_s': float((s + md['window_len']) / md['fs']),
                'class': pred_labels[i],
                'probs': dict(zip(md['classes'], probs[i].round(3).tolist())),
            }
            for i, s in enumerate(starts)
        ]

    return result


# =========================
# TEST
# =========================
print('\n=== TEST load_model + predict_signal ===')
model_dict = load_model(WEIGHTS_PATH)
print(f'Wczytano model | klasy: {model_dict["classes"]} | fs={model_dict["fs"]}')

try:
    rec = wfdb.rdrecord('208', pn_dir='mitdb')
    result = predict_signal(rec.p_signal[:, 0], model_dict, return_windows=True)
    print(f'Dominująca klasa : {result["majority_class"]}')
    print(f'Pewność          : {result["majority_prob"]:.1%}')
    print(f'Rozkład klas     : {result["class_distribution"]}')
    print(f'Liczba okien     : {result["n_windows"]}')
    for w in result['window_results'][:3]:
        print(f'  {w["start_s"]:.0f}s–{w["end_s"]:.0f}s → {w["class"]} | {w["probs"]}')
except Exception as e:
    print(f'Test pominięty: {e}')